# -*- python -*-

def testbase(env):
    env.Append(CXXFLAGS=['-std=c++14'])

env = Environment(tools=['default', testbase])

env.Append( LIBS = ['gtest_main', 'gtest'])

sources = Split("""
naiipm_gtest.cc
""")

env.Program(target = 'g_test', source = sources)
