# -*- python -*-
import sys

if sys.platform == "darwin":
    def testbase(env):
        env.Append(CXXFLAGS=['-std=c++14'])
        env.Append(CPPPATH='/opt/homebrew/include')
        env.Append(LIBPATH='/opt/homebrew/lib')
    env = Environment(tools=['default', testbase])
else:
    env = Environment(tools=['default'])

env.Append(LIBS = ['gtest_main', 'gtest', 'gmock'])

sources = Split("""
cmd_gtest.cc
argparse_gtest.cc
naiipm_gtest.cc
measure_gtest.cc
status_gtest.cc
record_gtest.cc
bitresult_gtest.cc
""")

env.Program(target = 'g_test', source = sources)
